spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.filter.create: All tasks

camunda.bpm:
  run.cors:
    enabled: true
    allowed-origins: "*"

camunda.bpm.admin-user:
  id: demo
  password: demo